export const team = [
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Farhana",
        bio: "#",
        website: "",
        github: "",
        linkedin: "",
    },
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Joe",
        bio: "#",
        website: "",
        github: "",
        linkedin: "",
    },
    {
        image: "https://marekgrabowski.net/_astro/profile_photo.dc0b9a6b_Z24pAQE.webp",
        name: "Marek Grabowski",
        bio: "Marek is an undergraduate Computer Science student at CCSU, anticipating graduation in May 2024. In this project, he made significant contributions to the front end, responsible for designing the site layout and many of its components. He also assisted in implementing various security and authentication features and internal API. Besides his interests in Computer Science, Marek currently works as an AV System Engineer & Programmer.",
        website: "https://marekgrabowski.net/",
        github: "https://github.com/marekgrabowski",
        linkedin: "https://www.linkedin.com/in/marekgrabski/",
    },
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Michael",
        bio: "bakend guy",
        website: "",
        github: "",
        linkedin: "",
    },
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Minh",
        bio: "#",
        website: "",
        github: "",
        linkedin: "",
    },
];