export const team = [
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Farhana Yasmin",
        bio: "Farhana Yasmin, a senior enrolled in the Computer Science program at Central Connecticut State University, is on track to earn her Bachelor's Degree in 2024. Her academic journey began with the successful attainment of an associate degree in Computer Science, accompanied by an academic award from her department. Beyond her major, Farhana is actively pursuing a minor in Mathematics while concentrating her studies on cybersecurity. Her extensive coursework and project experiences have equipped her with a robust skill set. She possesses a profound understanding of Java skills, mastering core concepts,object-oriented principles, proficiently utilizes Java graphics libraries like JavaFX and Swing, excels in GUI programming, and demonstrates exceptional expertise in handling exceptions. Furthermore, she boasts proficiency in implementing HTML and CSS, comprehends web principles, and excels in JavaScript. Her unwavering dedication and strong work ethic fuel her drive to excel in her chosen field.",
        website: "",
        github: "https://github.com/fyasmin02",
        linkedin: "",
    },
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Joe Conticello",
        bio: "Joseph Conticello is currently a senior in the Computer Science program at Central Connecticut State University and will receive his Bachelor’s degree in December of 2023. He is currently interning at OWIT Global as a Quality Assurance Automation Engineer. Joe is also an accomplished jazz pianist and composer, holding a Bachelor’s Degree in Music Performance from Western Connecticut State University, where he also worked as an adjunct professor. He enjoys bringing a unique and creative perspective to his work space, and prides himself on his ability to be both an effective leader and lifelong learner.",
        website: "",
        github: "https://github.com/JC2197",
        linkedin: "",
    },
    {
        image: "https://marekgrabowski.net/_astro/profile_photo.dc0b9a6b_Z24pAQE.webp",
        name: "Marek Grabowski",
        bio: "Marek is an undergraduate Computer Science student at CCSU, anticipating graduation in May 2024. In this project, he made significant contributions to the front end, responsible for designing the site layout and many of its components. He also assisted in implementing various security and authentication features and internal API. Besides his interests in Computer Science, Marek currently works as an AV System Engineer & Programmer.",
        website: "https://marekgrabowski.net/",
        github: "https://github.com/marekgrabowski",
        linkedin: "https://www.linkedin.com/in/marekgrabski/",
    },
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Michael",
        bio: "Michael Cox is a senior studying Computer Science at Central Connecticut State University, expecting to graduate in May 2024. He has been working as a Machine Vision Programmer at Alta Vision Systems in Westbrook CT full time during summers and part time during college for over 1 year. In this role, he has designed and programmed .NET WPF applications in C# where he specializes in following the MVVM pattern and is adept at integrating machine vision software to deliver high-quality solutions for complex visual analysis tasks. He is always searching to learn new design patterns to create modular and maintainable software.",
        website: "https://github.com/michaelcox3",
        github: "",
        linkedin: "",
    },
    {
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        name: "Minh Tram",
        bio: "Minh Tram is a senior studying Computer Science Honors program at Central Connecticut State University and expecting to earn his Bachelor of Science degree in June 2024. He is a pre-intermediate experienced aerospace computer numerical control (CNC) machinist and familiar with GD&T, Metrology, and G-Code programming. His ongoing, positive, and quick-witted personality made him highly efficient at work and willingness to put himself in other’s shoes. He is always looking for any opportunity that will improve his capabilities, expand his knowledge, and make a meaningful impact on other people’s lives and communities.",
        website: "",
        github: "https://github.com/minhctram",
        linkedin: "",
    },
];
